### ISSUE TITLE
App becomes frozen when the settings icon is clicked

### ISSUE THREAD

**Issue by quantumrhombus** [Thomas101/wmail#156]
The app works fine until I click the settings icon. The app then becomes frozen, except for the three window dots in the top left corner.
Version 1.3.0, mac

**Comment by Thomas101** [comment]
If you restart the app do you still see this problem?

**Comment by schmuto** [comment]
I have the same problem, even after I restarted the app.

**Comment by Thomas101** [comment]
Hmmm. Weird. I'm not seeing the issue. If you go to wmail in the app bar and then preferences does that work?

Also cab you open developer tools by going to view>developer tools, then press the settings button and take a screenshot of any error messages that come out (there will be a coupe of warnings from the react-color library)

**Comment by schmuto** [comment]
![bildschirmfoto 2016-05-08 um 21 36 28](https://cloud.githubusercontent.com/assets/10495193/15099950/f7992db2-1564-11e6-9e2c-8dcf0947ce6c.png)

**Comment by enobrev** [comment]
Same issue and same console errors on Ubuntu 15.10 (x64).  Saw these issues last week on a react project after upgrading to 15.x.  Ended up having to downgrade react to 0.14.x while waiting for a couple dependencies to catch up.

**Comment by yoswa** [comment]
Same issue and console errors using 1.3.0 on Mac 10.11.4. But a reinstall seems to fix this.
I deleted the app and all related folders using appcleaner. Redownloaded and reopened. Then it still popped up some warnings but the settings is visible now.
![schermafbeelding 2016-05-09 om 08 32 26](https://cloud.githubusercontent.com/assets/8811826/15105358/4d021618-15c1-11e6-9cd4-b650cce08be6.png)

**Comment by Thomas101** [comment]
Okay, I see the same issue now. Thanks for finding that. I'll put a patch together and get another release done later today! The issue is with having it not ask the download location every time. It looks like updating to react 15.x from 14.x has changed the behaviour of this slightly.

In the meantime if you still want to use the settings here's what you can do....
Go to view > Developer Tools. Then at the bottom of the warnings where you see a little blue arrow you can click and type in there. Paste the following and press enter

```
localStorage.App_settings = JSON.stringify(Object.assign(JSON.parse(localStorage.App_settings), { defaultDownloadLocation: '', alwaysAskDownloadLocation: true }))
```

then restart your app. If you change the download setting again you'll end up in the same scenario. Alternatively if you hang on without settings, just hold tight and grab the newer version later on :)

**Comment by Thomas101** [comment]
This fix is now live. You can download 1.3.1 from the [download page](https://thomas101.github.io/wmail/download). Thanks for reporting the bug!
