### ISSUE TITLE
Hiding credentials

### ISSUE THREAD

**Issue by TimNZ** [Thomas101/wmail#168]
The Google credentials can be extracted from the built mailbox.js

I've only started playing with Electron so don't know much but is there a way to obfuscate them.

I realise generally storing credentials in a locally run app is never safe but in this case a little too easy to find..

**Comment by Thomas101** [comment]
Hi, obviously security is very important as WMail deals with e-mail accounts which can contain sensitive information. The trouble with any app that gets installed is it's way too easy to find secret keys etc. If for example you compile it into a c binary, you can use `strings` to extract all the strings from the app. If you use Java you could decompile the code. If you lock it behind some encryption, you still have to ship the key with the app so anyone determined enough to steal your key can get it with relative ease.

I could obfuscate the credentials but in doing so, to allow others to build the app from source I would have to provide instructions on how to do this, which would involve giving away the secret sauce on how to undo it. Even if I didn't provide these instructions, it's also reasonable to assume that if someone is skilled enough to know how to grab the credentials, either from the run-time or saved bundle they are skilled enough to dig through enough code to decode it and know how to use it.

This is a common problem to not just using authenticated google apis, but also other platforms that use similar systems. [Google are very clear in their documentation](https://developers.google.com/identity/protocols/OAuth2InstalledApp#overview) that even though it's called a secret key, they assume that it really isn't because of this exact problem.

The only way to really protect the secret key would be to run some private code in the cloud that keeps the client id and secret a real secret from the installed application. This does have the side effect that the service has to handle account access tokens at some point during its lifecycle and also all google communication has to run through this service, which then from googles end runs into other problems such as bandwidth limiting and quotas.

The client ID and Secret is used for OAuth which is really setup to protect the user from unauthorized access rather than prevent service impersonation. It does this by removing the need to supply your username and password to a 3rd party and also giving the ability to control and revoke access to 3rd parties you've granted access to.

If you do have any suggestions on how to make the app more secure, obviously I'd be happy to look into them or merge pull requests.

**Comment by TimNZ** [comment]
Thanks for the detailed reply.

In my case this isn't an issue as I am repurposing the app for a totally different scenario but it may become a problem later on.

Your code as starter has been immensely valuable and a huge timesaver, it just happened to have a lot of what I needed for my app's architecture.

I'll be making a significant 'beer' contribution as soon as I start earning revenue!
