### ISSUE TITLE
Blank Window after entering GMail account info

### ISSUE THREAD

**Issue by lynetta** [Thomas101/wmail#226]
After unzipping the app on Ubuntu 14.04, and moving through the setup for a gmail account the only thing I see is my account pic off to the far right column at the top and a plus icon and settings gear near the bottom of the column.  Otherwise I see a white screen.

Am I doing some thing wrong?

**Comment by Thomas101** [comment]
Hi which version of WMail are you using?

**Comment by lynetta** [comment]
I added my gmail account, and saw nothing, but then today I opened the app again and everything appeared.  I tried another account and saw the same thing; when adding the account nothing appears on the right side (main part of the window) but after exiting the app and going back in everything showed as expected.  It is a glitch but totally manageable.  The zip file is WMail_1_31_linux64.zip.

**Comment by Thomas101** [comment]
Have you tried the 1.3.5 pre-release? This may fix this issue

**Comment by samaphp** [comment]
I just want to confirm this issue, I've just installed WMail_1_3_5_linux64.zip and after I added 2 Gmail accounts the side bar being cut off .. then when I'm reading issue #211 I saw some of them suggest to press Cmd+R to refresh the page. Then after I press Ctrl+R the window just being blank. I tried to refresh again and again but it is still blank page.

Please how can I uninstall the app and install it again, because I just download another version 1.3.4 but it has the same issue, so I thought this might be related to data stored for the App?

Thank you very much for this amazing App .. I really love it. Keep it up.

**Comment by samaphp** [comment]
I just logged-off my computer and logged-in again and it worked nicely now. I suggest to use this app in Unity not in Gnome Flashback Metacity to have the top menu of Unity. Also it might related to the first setup of a new Gmail account or first app open. Because the performance now is much better when resizing window.
Thanks

**Comment by Thomas101** [comment]
I've just given this a go, but it worked fine for me. @samaphp were you using Gnome the first time you tried?

Could either of you try the following...

1.) Delete `~/.local/share/wmail`
2.) Launch the app
3.) Go to `View > Developer Tools` / use `Ctrl+Alt+J`
4.) Press the `console` tab
5.) Re-add your first account and see if any errors come up?

Thanks

**Comment by samaphp** [comment]
The first time was in the same hour (Gnome Flashback Metacity) then when this issue happen I switch to Unity and it work .. I go back to (Gnome Flashback Metacity) and it's worked well also.
I tried to reproduce this issue after side and top hide and I press on Ctrl+R and tried a lot but it wont happen again. I believe the issue still there but still can not reproduce it. I will keep trying and will update this issue soon.

I think this maybe in settings, is there some setting reset after log-off? maybe saved temporary?

Many Thanks :heart:

**Comment by Thomas101** [comment]
Okay thanks! All the settings should be persisted to disk, so they should load up the same next time. It sounded like the app got into an unknown state and then ended up not doing something correctly.
