### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by TimNZ** [Thomas101/wmail#230]
Hey mate, trying to debug an issue with webview not persisting sessions even with 'partition="persist:xxxxxx"' set on it, in an app I am developing.

Since I know yours works, downloaded 1.3.4 and had a lot of trouble getting to point of it building

* Stumbled across your commit message re typo patch and downloaded and copied across your fork
* At startup there is a bug where StorageBucket._handleIPCSetItem is called for key = 'language', body = {}, resulting in [object Object] being persisted to settings_db.json because setItem does this: this.__data__[k] = '' + v.  The app that hangs on start due to unable to JSON.parse this.  Have changed setItem to "this.__data__[k] = v" and that appears to work.
* In settingsStore.js all persistence.on(...) handlers set this.language = ... (copy and paste issue)

The whole StorageBucket/persistence setup looks even more complex/convoluted than last time I looked - how do you keep track?? :)

The good news is your sessions are persisted across app restarts.
The bad news is I can't figure out what the hell is going on with my tests.

**Comment by Thomas101** [comment]
Hey,

The database bits are a bit shaky in the latest pre-releases after a huge refactor in 1.3.2. The json parsing bits you mentioned were fixed in 1.3.5. (See commit https://github.com/Thomas101/wmail/commit/ab2f27942bb3e8a10f5900bcf152692df9023f30).

As regards the webview not persisting I have noticed that when using a google apps account you normally have to open the "You've signed in from a new computer" email to get it to persist. I think it's some security thing with Google. Don't know if that helps?

Onto the database bits. I've been doing some work here as there have been some performance and memory leak issues. It's probably going to change again in the next pre-release to squash the remainder of these. As to the complexity, it's down to the multi-threaded architecture of electron and the inherent non-multithreadedness of javascript. The core database actually sits in the main thread, however the rendering thread needs access to it. To achieve this I was just blocking the two threads and making calls synchronously in 1.3.1, however I've updated this to use asynchronous IPC calls now. Here's a rough outline of how it works...

1. Main point of access, the alt-stores. (e.g. `scenes/mailboxes/src/stores/mailbox/mailboxStore.js`). This provides an in memory cache and the logic for transforming the data as required. When the data changes it's pushed through to number 2.

2. An instance of `scenes/mailboxes/src/stores/StorageBucket.js`. This provides synchronous & asynchronous calls to the main thread. It obfuscates the underlying transport so that calling `getItem` just returns a promise (or just returns if sync) when the data is available meaning your normal code doesn't need to worry about the threads etc

3. An instance of `app/src/app/storage/StorageBucket.js`. This answers the IPC calls that are made from the rendering thread, processes them and responds as required. This does the actual database heavy lifting (writing to disk etc). It also emits some events, to which code in the main thread listens. For example mailboxes changing has an effect that the app menu is updated.

Have a look at the [ipc-main docs](https://github.com/electron/electron/blob/master/docs/api/ipc-main.md) in particular the `Sending Messages` section. This is an example of how async and sync comms can happen between the main thread and rendering thread. This is what I've used.

In the next version I'm looking at splitting the mailbox model out into two, so that the unread google messages are stored separately from the actual mailbox. This should reduce the amount of data that's re-written to disk. I'm going to do some performance testing beforehand to see if a key value store will provide better throughput too, I suspect it's going to be a complete overkill for this but you never know.

**Comment by 7krasov** [comment]
Hi,

I have an issue on Ubuntu 16.04, WMail v. 1.3.1. When I'm logging into Ubuntu and WMail is starting before internet connection set, I'm having a hanging state of accounts: their content part of window look absolutely empty and nothing is changing after setting of internet connection. I'm trying to wake them up clicking on circles of accounts but no result. To fix it I have to reload app: close application, kill about 7 processes an run it again.
