### ISSUE TITLE
overlap with inbox-app

### ISSUE THREAD

**Issue by plessbd** [Thomas101/wmail#25]
seems like this project has a lot of overlap with https://github.com/fgnass/inbox-app

I wonder if the two could merge or collaborate to produce a great app.

**Comment by avelis** [comment]
+1 For collaboration but then again I am a user and not a collaborator so I have no authority future progress of either app.

**Comment by vitorgalvao** [comment]
I see no reason why they should merge, or what kind of greater app could emerge from such collaboration. All these are doing (and all they can do) is put an application wrapper around a webpage.

There’s nothing to be gained from joining up. Deprecating one in favour of the other (the other one would currently make more since since it apparently can do less) would make more sense, but then again, why do it? Each creator made the app they wanted, and they can both exist separately. Together, however, they’d be the same, not better.
