### ISSUE TITLE
new icon 1.3.7

### ISSUE THREAD

**Issue by sakshamgoyal01** [Thomas101/wmail#271]
new icons dont work!!

![image](https://cloud.githubusercontent.com/assets/19929553/18034483/880dccda-6d68-11e6-96d3-4894c2225e01.png)
![image](https://cloud.githubusercontent.com/assets/19929553/18034491/9e89d238-6d68-11e6-8294-a6d618fd45dc.png)

windows 10 Wmail1.3.7

**Comment by Thomas101** [comment]
Are you still seeing this? I've tested on windows 10 and it seems to work. Are you using the 32bit or 64 bit version?

**Comment by sakshamgoyal01** [comment]
64bit not working

**Comment by Thomas101** [comment]
Have you tried restarting windows? If you uninstall the app and install it again does it come back?

**Comment by sakshamgoyal01** [comment]
have you made any changes to the coding of the icons? if so, try to revert them. mabye there is a bug? im not sure. after reinstalling

by the way, why isn't the normal installation gaining any updates? it is still on 1.3.1. is there some issue that is causing this?

**Comment by Thomas101** [comment]
The only change that was made was the icon was changed from being PNG to ICO but this wouldn't have any effect on the shortcut. Plus with a fresh install on my VM it works fine which is why I don't understand why the issue is showing up.

As for 1.3.1, I normally do 4 or 5 prerelease before bumping to the major version. This helps to reduce bugs in the primary release version. 1.3.7 is a good release candidate so I expect to push to the main release soon

**Comment by sakshamgoyal01** [comment]
i'm not sure why this is happening, i have reinstalled multiple times but its not working.

**Comment by Thomas101** [comment]
I can't seem to reproduce this in any way across 3 different copies of window. I would suggest trying the next version of wmail when it lands -- if not try setting the shortcut icon separately
