### ISSUE TITLE
Menu bar icon is low resolution on 4K/retina display 2

### ISSUE THREAD

**Issue by Martindelataille** [Thomas101/wmail#281]
This issue is coming back.

<img width="76" alt="capture d ecran 2016-08-30 a 15 47 09" src="https://cloud.githubusercontent.com/assets/1131616/18091471/0807cc72-6ec9-11e6-9611-0e18747b43cf.png">

It seem to have been fixed in #166 

When i type ``window.devicePixelRatio``, i get "2" on a retina display

**Comment by cdysthe** [comment]
Same on a 4K display running Ubuntu 16.04 x64. It's even visually "grainy".

**Comment by Thomas101** [comment]
I've added in a selector so you can pick the dpi you want to support because it doesn't look like devicePixelRatio is a good enough indicator. Will be out in the next release :)
![screen shot 2016-09-07 at 19 34 46](https://cloud.githubusercontent.com/assets/103586/18324017/3f62ba8c-7532-11e6-9368-bbdf8616f8a9.png)

**Comment by Thomas101** [comment]
Hi, thanks for reporting this, this has been fixed/added in the latest pre-release which you can download [here](https://github.com/Thomas101/wmail/releases/tag/v1.3.8)
