### ISSUE TITLE
new UI, spellcheck

### ISSUE THREAD

**Issue by sakshamgoyal01** [Thomas101/wmail#285]
new UI for windows that looks similar to mac style? seemless windows to the edge, curved edges? (like the picture in the readme.md)
right click to see spelling recommendations
ad blocker?

windows 10 64bit wmail1.3.7

**Comment by Thomas101** [comment]
The mac window style along with the seemless windows are only supported on osx by electron. Spelling recommendations have been supported since 1.2.0. Ad blocking is out of scope of this project and definitely falls into the extensions category which as more info in the [FAQs](https://github.com/Thomas101/wmail/wiki/FAQs)
