### ISSUE TITLE
Different versions don't play nicely with each other when installing/uninstalling

### ISSUE THREAD

**Issue by Eldaw** [Thomas101/wmail#286]
With v1.3.1 installed on Windows 10 x64, I decided to install the 1.3.7 pre-release (x64). Unfortunately, it added a separate entry to my programs list in:
Control Panel\Programs\Programs and Features

Annoyed by having 2 entries for WMail, I then decided to uninstall 1.3.7.

But now that I've launched 1.3.1 again, I see that the uninstallation of 1.3.7 has wiped out my configuration, and all of my mailboxes that were in 1.3.1 are now gone.

**Comment by Thomas101** [comment]
Hi,

Sorry about the trouble you've been having. Unfortunately I've had to change the way the installer is generated in the latest set of pre-releases because it was taking me approximately 5 hours to get a release ready. This does have the side effect of needing to uninstall the old version of the app before upgrading.

As regards reverting back to 1.3.1 the latest pre-releases use an updated version of the user data which is not backwards compatible with older versions.

I've added a warning in the release notes about needing to uninstall any previous versions of WMail (there will be more detailed instructions when I make the next major release) and I've added a wiki page with instructions on how to backup your data when trying out a prerelease in case you need to go back to an older version.

**Comment by Eldaw** [comment]
OK, Thanks Thomas. I've managed to restore my configuration/data files for v1.3.1 from a full system backup performed yesterday.
