### ISSUE TITLE
Multiple dictionaries at once

### ISSUE THREAD

**Issue by vitorgalvao** [Thomas101/wmail#288]
Thank you for https://github.com/Thomas101/wmail/issues/139! Since I write in two languages regularly, could we add multiple dictionaries at once, instead of having just one?

Wmail 1.3.7 on macOS 10.11.6.

**Comment by Thomas101** [comment]
This is a nice idea! I've got a bunch of work to do with the spellchecker which is looking like switching the library out for a different one because of #252 #279 #277 #275. If I can get what I'm thinking of working across platforms it should make the architecture of the whole spellchecking simpler and remove the need for the app to restart which would in turn make this much easier.

I'm going to mark it for the 1.3.8 milestone because I'll need to make some breaking changes to the way I do the custom dictionaries which I would rather get over with between prereleases rather than major releases... however depending on how tricky it is, it might not make it out until 1.3.9.

How do you think it would be best to switch between dictionaries? If you could just just go to settings and pick your language would that be easy enough? (no 3 step download & app restart).

**Comment by vitorgalvao** [comment]
I was thinking simpler: having a `+` to add more, and they’d all be in use at the same time, no switching.

**Comment by Thomas101** [comment]
Not 100% sure how this will work, but I'll take a look

**Comment by vitorgalvao** [comment]
That was fast! Thank you.

**Comment by Thomas101** [comment]
Don't thank me until it's released and working ;-)

**Comment by vitorgalvao** [comment]
Still thanking you for picking up the request, and so quickly.

**Comment by Thomas101** [comment]
Hi, thanks for reporting this, this has been fixed/added in the latest pre-release which you can download [here](https://github.com/Thomas101/wmail/releases/tag/v1.3.8)

**Comment by Thomas101** [comment]
@vitorgalvao out if curiosity which two languages have you been using?

**Comment by vitorgalvao** [comment]
English (UK) and Português (Portugal). I use both frequently.

**Comment by Thomas101** [comment]
That's fine - just wanted to check because I've noticed there are some incompatibilities between languages that have different character sets
