### ISSUE TITLE
[FEATURE REQUEST] Master password

### ISSUE THREAD

**Issue by almostmavron** [Thomas101/wmail#315]
Version: 1.3.8 prerelease
Operating System: Kubuntu 14.04 LTS, updated

When you open WMail, you automatically gain access to all of your logged-in accounts, which can vary from company account to different personal accounts; in my case I have two (company and personal), other people have more.

Although this multiple unprotected access to email is somewhat mitigated by having to log in into your computer in the first place (and maybe by having a password-protected screensaver), sometimes is acceptable to leave your computer for use to someone else, be it a family member or colleague or younameit.
That's expecially true in a work context, where IT people can ask to use your computer with your account logged in, in order to fix some problem your user might have.

Anyway, in such a scenario, that does not mean you want this (even trusted) person to gain unprotected access to ALL of your email accounts.
Having to login into all of them every time is not an option for anybody, I think.

A compromise could be the possibility to set a (optional) master password in order to gain access to your WMail profile.
The perfect feature would encrypt the files (all or just the critical ones) in your profile dir, in order to obtain a real protection (your profile, auth cookies, caches, etc) rather than a apparent one.

Inspiration (maybe even some JS code excerpt) could be drawn from a Thunderbird's extension:
https://support.mozilla.org/en-US/kb/protect-your-thunderbird-passwords-master-password

Thanks
Bye
Carm

**Comment by Thomas101** [comment]
I can definitely see the value in this. Encrypting the data that I drop on disk would be pretty easy however the data that chromium uses is where the problem lies.

WMail uses Chromium under the hood and that stores the cookies and localStorage data it uses to access Google straight on disk with no encryption. I could try encrypting this data, then decrypting when the password is entered so chromium can access and provide wmail with access to each account, however whilst the app is open or if the app were ever to quit unexpectedly it would leave the unencrypted data on disk for anyone to grab.

This obviously leaves a giant security hole. I don't imagine adding support for this is on the Chromium teams list and it would be a huge task to integrate this into Chromium from a 3rd party perspective.

From a technical perspective the only thing that I think would work without any security holes, is I could set wmail up to not persist the cookie data at all for a certain account (i.e. keep it in memory only). This would however mean that you'd need to re sign in to google every time you launch wmail. It's basically like going incognito and wouldn't provide any advantage over loading gmail in your browser.

Arguably I could overlook the potential security holes and provide a password block to prevent access to an account using wmail. However because the data is up for grabs on disk I wouldn't feel comfortable providing this level of assurance to users knowing that it could be so easily hacked.

I'll keep an eye on the tech stack going forwards though. In an ideal world I would love to be able to add this, but at the moment it's not technically feasible.
