### ISSUE TITLE
Freezing / locking up

### ISSUE THREAD

**Issue by getthemike** [Thomas101/wmail#319]
* Which version of WMail are you using? 1.3.8 - was occurring with previous versions as well

* Which Operating System are you using? Mac OSX 10.11.6

Dev tools gives this error:
Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError

Sounds like it might be related.

**Comment by Thomas101** [comment]
Hi, I've just put out the [1.3.9 prerelease](https://github.com/Thomas101/wmail/releases) which has an updated version of chrome under the hood. Do you still see the same issue with this version?

**Comment by getthemike** [comment]
Nope appears to be better.

**Comment by Thomas101** [comment]
Awesome! I'll close this off then :)

**Comment by getthemike** [comment]
I may have spoke to soon. I'm seeing some freezing again.

**Comment by Thomas101** [comment]
Darn. Okay, how many accounts do you have and roughly how many unread messages?

**Comment by getthemike** [comment]
One account. 8 unread. I am logged in with both Gmail and Inbox though.
What other info can I give you?


 - mike searcy <http://mikesearcy.com/> #502.252.3588

**Comment by Thomas101** [comment]
This is a difficult one. I've taken a look at other reports of the error you mentioned but nothing conclusive comes up on google. There's a couple of mentions that it's because there's too many file & network refs open. Aside from what chromium has open it should only have up to 4 or 5 files open and maybe up to 3 or 4 network requests at any one time. Anyway lets see if something's gone wrong with the database access...

If you open up `~/Library/Application Support/` what size is the `wmail` folder?

In the `wmail` folder what size are the files ending in `_db.json`? There should be `mailboxes_db.json`, `settings_db.json`, `avatar_db.json` and maybe `app_db.json`

Next lets see if it's wmail not mixing well with something else. If you restart your mac, don't open any other app and just keep wmail open do you still see the issue?

When would you say it freezes up, just all the time, when typing, when navigating around gmail/inbox?

Thanks!

**Comment by getthemike** [comment]
So without going too far down the wrong path:

> https://inbox.google.com

Is struggling right now. How can google do a good thing so poorly?

I think I should not dig any deeper without isolating Google server
problems.


 - mike searcy <http://mikesearcy.com/> #502.252.3588

**Comment by Thomas101** [comment]
I'm guessing this is happening in your web browser then?

**Comment by getthemike** [comment]
Yeah. It seems like Inbox just has crappy performance in general which is
weird because Google always focused so hard on Gmail being blazing fast.


 - mike searcy <http://mikesearcy.com/> #502.252.3588

**Comment by Thomas101** [comment]
Hopefully google will make some fixes soon and this should go away. I'll close this off for now as it's more of a google performance issue. Thanks!
