### ISSUE TITLE
Bug: Attaching high resolution PNG files to email results in black window

### ISSUE THREAD

**Issue by andrew-dc** [Thomas101/wmail#339]
* Which version of WMail are you using? 1.3.1

* Which Operating System are you using? Windows 10

When I try to select attachments from my computer and select a couple of high resolution PNG images (containing transparency), the Wmail windows goes black. It doesn't seem to have an issue with lower resolution PNG files or other file types.

Screenshot: https://i.imgur.com/XN4dM0a.png

**Comment by Thomas101** [comment]
Hi I've just tried this but I can't seem to reproduce it. Was this with Gmail or Google Inbox?

Are you able to send me the png that you used? If not can you give me the image dimensions and filesize?

I used these two images for testing...
http://vignette3.wikia.nocookie.net/althistory/images/f/f1/Burma_Ascension_World_Map_Prototype.png/revision/latest?cb=20120214140500
http://pngimg.com/upload/lion_PNG3805.png

**Comment by andrew-dc** [comment]
Hey, I tried attaching 3 images all similarly sized, the largest was 17813 by 25142 pixels, with a filesize of 5.55 mb. This was in Google Inbox, I tried using the browser version and was able to successfully attach the files there, but Wmail couldn't for some reason.

**Comment by Thomas101** [comment]
Wow that is a big image! I've tried on osx and windows and although it's extremely slow it does just about work.

Normally when it goes black like that it's because the gpu thread crashes. I suspect although it works in chrome there's probably something slightly different in the chromium version that wmail uses.

Unfortunately with an issue like this the reliability of the bug will be down to a combination of hardware, drivers and free resources. I suspect if you close all applications and try again you may see a little more success, but then again you may not.

I hate to say it, but there may not be a definitive resolution on this. It's definitely an issue with the underlying tech that's being used. Probably my best suggestion on this is upgrade to the prerelease as this has a newer version of chromium under the hood - although you may well see the same issue.

Sorry I can't offer anything more solid!

**Comment by andrew-dc** [comment]
That's alright, I suspect this is a fairly rare set of specific circumstances anyway and I can definitely live with it. Keep up the good work!

**Comment by Thomas101** [comment]
Thanks :)
