### ISSUE TITLE
Problem with expired login

### ISSUE THREAD

**Issue by domoritz** [Thomas101/wmail#345]
* Which version of WMail are you using? 1.3.9
* Which Operating System are you using? Mac OSX 10

From time to time the login for my university account seems to expire. In my browser, I would just navigate back to get to the login page again. However, that does not work in Wmail. 

![screen shot 2016-10-04 at 13 05 43](https://cloud.githubusercontent.com/assets/589034/19090456/6ca4a77e-8a33-11e6-8b90-c2ea30f9b8ce.png)

Deleting and adding the account again works but I'd prefer some way to navigate back to get back to the login. I also tried deleting all cookies from the developer console but without success.

**Comment by Thomas101** [comment]
That will probably be the server rejecting the expired cookies. You didn't happen to leave the window open?

**Comment by domoritz** [comment]
I did not keep the account around. However, it will probably happen again in a few weeks. I'll come back when this happens.

**Comment by Thomas101** [comment]
Thanks. I'm wondering if I can auto-detect a logout state. Alternatively it might be down to adding a  re-login button in a context menu.

**Comment by domoritz** [comment]
A re-login button would be great.

**Comment by Thomas101** [comment]
I've added an option in to the account menu on the left. Not ideal but at least it will get you un-stuck. I'm hoping it will work as it just nukes all the cookies etc. Hopefully if I can detect a logged-out state in a relatively general way I can bring something up to offer it :)

![screen shot 2016-10-06 at 17 53 35](https://cloud.githubusercontent.com/assets/103586/19162009/073a23de-8bee-11e6-9a14-cb2007609bc1.png)

**Comment by BenJetson** [comment]
I'm experiencing the same issue with the cookie persistence on a couple of my machines and can confirm that re-adding the mailbox does work (while extremely inconvenient). I'm running WMail version 1.4.0 prerelease on both Windows 8.1 and Ubuntu MATE 16.04. 

The behavior I am seeing is this: 
When WMail opens and I choose the expired account from the sidebar on the left, the Google login page appears instead of the mailbox. I enter my username at the prompt and login through my organization's SAML login page. Normally after a successful sign in I am instantly redirected to the Google web app I was looking for. Unfortunately in this case, the login fails and I am presented with this error from Google about cookie settings:

> ![image](https://cloud.githubusercontent.com/assets/10427974/19498971/d2d144d8-9561-11e6-8d96-6c93d06d7e29.png)

I've still got the broken mailbox around for now and would be willing to beta test the logout-state detection or other solutions with you.

**Comment by Thomas101** [comment]
@BenJetson do you still have the logged out mailbox in wmail? If you do it would be great to get the url it fell out to.

**Comment by BenJetson** [comment]
I pulled the URL from the inspector console:

![wmail-logout-url-inbox](https://cloud.githubusercontent.com/assets/10427974/19529422/cc20b74e-95fd-11e6-9d31-37b80ca072aa.png)

**Comment by domoritz** [comment]
Reauthenticating doesn't seem to help. I'm still seeing the error.
