### ISSUE TITLE
Running the installer doesn't fully install WMail

### ISSUE THREAD

**Issue by Eldaw** [Thomas101/wmail#350]
v1.4.0 on Windows 10 x64.

Each time when I run the installer for a new prerelease version of WMail, it doesn't actually get fully installed. After the installer finishes, the shortcut for WMail that is pinned to my taskbar loses its icon, meaning it's pointing to nothing anymore.

Then if I open the Start Menu and right-click on the entry for WMail, the context menu that appears doesn't contain the usual options such as 'Pin to Taskbar'. If I click on the WMail entry in the start menu, then I get one of those 'Please wait while Windows configures WMail' dialog boxes that indicates an application is being reinstalled or reconfigured after a major change. After that second installation runs and completes, only then am I able to start the application and access context menu commands on the shortcut to re-pin the shortcut to my taskbar, etc.

Today, with v1.4.0 I had actually moved the installation executable after doing the "first installation". Then, when I tried to launch it from the start menu, when the "second installation" started I got one of those standard dialogs prompting me for where it can find the file 'WMail_1_4_0_prerelease_windows_x64.msi'

**Comment by Thomas101** [comment]
That's really odd. I do see the same though. I'll do a bit of digging to find out what's happening. Thanks!

**Comment by Thomas101** [comment]
After some heavy googling it looks like this happens when the install fails [see reference](http://stackoverflow.com/questions/8283990/windows-installer-doesnt-finish-installing-until-after-application-shortcut-is). When you try to open the app windows then recovers the install and continues it. It's just handy that it doesn't tell you about it!

Anyway I've updated the toolchain that I use to make the installer on my machine and it seems to work okay now. I'll close this off, but if you see the same issue when you install the next version feel free to let me know.

Thanks!
