### ISSUE TITLE
OS X: Context menu uses wrong key(s)

### ISSUE THREAD

**Issue by singerb** [Thomas101/wmail#392]
WMail 2.0.0, OS X

In order to bring up the context menu on the account icons in the sidebar (i.e., to remove an account), you have to control-click on the icon. The following two things, which are what a normal Mac app would use, don't work: command-click, two finger click.

**Comment by Thomas101** [comment]
Hi, I've updated the click handler so when you use cmd+click it opens the settings directly. osx uses ctrl+click as right click so I felt this was a more appropriate action rather than just bringing up the menu. As regards the two finder click this is handled entirely by the osx so it' down to what's setup in your system preferences.

**Comment by singerb** [comment]
Thanks, and you're right about the command click. My bad.
