### ISSUE TITLE
Idea: Accessing extensions?

### ISSUE THREAD

**Issue by rich-tie** [Thomas101/wmail#401]
Wmail looks great - I've been looking for exactly this type of application for a long time.

I use a CRM extension in my gmail (streak), however this (obviously) doesn't load in wmail. As Wmail is built on Chromium, can I guess this is something that will never be possible?? 

This would address a lot of the open ideas such as delayed send, email tracking etc etc

* Which version of WMail are you using? [2.0.0]
* Which Operating System are you using? [Windows 10]

**Comment by Thomas101** [comment]
Hi, all the chrome apis are from Google Chrome rather than Chromium. Theoretically there's no reason why you can't port these across - it's just a huge job to provide blanket support for any kind of extension so at the moment it's not something I'm looking at adding. However if there are developers looking at bringing their extension into WMail that's something that is going to be more achievable. I've added some more info in the [FAQs](https://github.com/Thomas101/wmail/wiki/FAQs#chrome-extensions)
