### ISSUE TITLE
Not able to select second spell dictionary

### ISSUE THREAD

**Issue by abashev** [Thomas101/wmail#402]
* Which version of WMail are you using? [e.g. 1.3.1]
2.0.3 prerelease

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
10.11.6

I've installed new dictionary for doing spell check in Russian but I'm not able to check in dropdown menu - it was grayed out. 

![image](https://cloud.githubusercontent.com/assets/214171/19786043/acee8c68-9ca4-11e6-9d8f-b462314f1737.png)

**Comment by Thomas101** [comment]
Hi, unfortunately this is because both spell check languages need to use the same character set. English uses Latin and Russian uses Cyrillic which means they're not compatible.

I did try to add support for multiple character sets but chromium doesn't have provide any support for it and it's not something they're looking at adding I'm afraid
