### ISSUE TITLE
cant logout from my account .

### ISSUE THREAD

**Issue by ahmadabd** [Thomas101/wmail#403]
Wmail looks great ,im using it from four month ago but in the lastest release it dosent have a place to click and logout from the account , i think it should 

* Which version of WMail are you using? [e.g. 1.3.1]
v2.0.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
ubuntu 16.10

**Comment by Thomas101** [comment]
Hi, logout intentionally isn't provided as WMail is meant to work more like a traditional email without login/logout etc. If you want to remove an account you can do this by right clicking on the account on the left hand side and choosing delete. In the latest prerelease a delete button is also provided in the settings screen.

**Comment by ahmadabd** [comment]
it s good :)
but i think its better to have some thing like password if we want , beacuse every one that may have access to my pc can run wmail and see my emails

**Comment by Thomas101** [comment]
Okay, I see where you're coming from.

So I have looked into  password protecting the app to exactly this use case, but because of the way chrome and electron work it's not possible to encrypt the browser data, which could be used to re-login to your account. Effectively putting a password in the app is as good as putting a gate over the road that you can just walk around.

Adding a logout button will be pretty much the same as all the auth tokens are still stored on your machine. Although you wouldn't be able to use them to login using the browser, there's no reason you couldn't use the tokens to make calls to the gmail api as you needed.

If you are concerned about other users accessing your account the best option here is to delete your account every time - removing all access from your machine. Alternatively you could use different user accounts in ubuntu. WMail stores the user data under the current users home directory.

**Comment by ahmadabd** [comment]
ok
thank you thumas :)
