### ISSUE TITLE
[BUG] Unread mode preferences not respected

### ISSUE THREAD

**Issue by braykov** [Thomas101/wmail#425]
* Which version of WMail are you using? [2.0.6]
* Which Operating System are you using? [Ubuntu 16.10]
This used to work OK in 2.0.5.
In preferences "Unread mode" has 4 values. I am using the first one - "All unread messages".
But now with that option, it shows me what is unread in my Primary tab.
The second option is "Unread messages in Primary Category" and it works correctly.
So it seams the first two options work the same.
I want to use the first option and see all my unread messages, regardless of their category.

In my GMail settings I have Inbos type: Default.

**Comment by Thomas101** [comment]
Hi, this is probably down to cec15454b48069ae2608f5d2c59cba89e0a50383 where I've started crawling the unread count from the gmail ui rather than off the notifications. I've done this to work around a bug on Googles end whereby the unread counts returned are incorrect.

I didn't really think there would be any call for using one Inbox type in gmail (e.g. Categories with Primary, Promotions etc) and getting an unread count for a different type (e.g. all). It's a perfectly valid thing to do though. I'll try and come up with something that allows both to work

**Comment by Thomas101** [comment]
Hi this should be fixed in the latest [prerelease](thomas101.github.io/wmail/download?v=2.0.7). Thanks!

**Comment by ffumarola** [comment]
@Thomas101 I'm in 2.0.7 and I checked to use the unread count from the UI and it doesn't seem to work. The unread count stays the same as the inaccurate way from before I checked that option.
