### ISSUE TITLE
Making Wmail the default email client

### ISSUE THREAD

**Issue by mikeperstin** [Thomas101/wmail#465]
* Which version of WMail are you using? [e.g. 1.3.1]
Pre-Release 2.0.7

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

Most main clients have a way to handle mailto: links and a way to make the mail client a default one on the OS (so that when you send a webpage it automatically forwards it to the mail client). Is there a way to implement that functionality on WMail?

**Comment by Dazzel** [comment]
Same goes for macOS. You are able to set the standard mail client to WMail but nothing happens if an mail link is clicked. Also WMail does not show up as an supported app at first.

**Comment by Thomas101** [comment]
Hi, this has been added in the latest [pre-release](https://thomas101.github.io/wmail/download?v=2.0.8). Thanks!

**Comment by ryandward** [comment]
Hi @Thomas101 although wmail does work as the default email client now, on OSX it does not open wmail if it isn't already open. Also, if wmail is not on the current desktop, OSX does not focus onto wmail. Instead, you have to manually move to the desktop where wmail is open, and then the new email message is ready to be composed.

**Comment by hogar1977** [comment]
Hi...

I have to report that in Antergos 2017.02. (linux distro) it does not work for me...
I have the latest version of the app installed, 2.1.1 and I am not able to set it up in Gnome 3.22 under 'Details' as a default email application - it is simply not offered.
The application itself has a launcher and is working perfectly fine, just this is not possible to do.

I find that strange because exactly that issue was solved in version 2.1.0 (or 2.1.1 I am honestly not sure any more) when I installed it in Ubuntu 16.10. This feature was available there - I was using the same version of Gnome, just the distro is now different... I don't know what else might affect. I know this issue is a regular pain in the ass to resolve on all platforms and distros bcs each and every one is handling things differently, but on the other hand it is a very important UI feature for an email client...

So what broke from version 2.1.0 to 2.1.1. :-)?

BR and excellent job until now - your mail client is exactly what I need! Access to drive, keep, contacts, etc from the app is a godsend feature!

**Comment by hogar1977** [comment]
As an afterthought - maybe you could look into gnome-gmail package and see how that is resolved there - that one is also using the web browser to access the gmail account. I have no idea if it is implemented in the similar way as your application or not, but that one never had such issues for me. It was always possible to select it as the default mail app and it was handling mailto links just fine.
