### ISSUE TITLE
Can't find wmail-spellchecker when build from sources

### ISSUE THREAD

**Issue by Martindelataille** [Thomas101/wmail#497]
When i try to package for osx, i get 
```
{ Error: Cannot find module '/Users/myusername/Projects/others/wmail/bin/app/node_modules/wmail-spellchecker/package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Function.packagerIgnoreString (/Users/myusername/Projects/others/wmail/packager/ElectronBuilder.js:48:31)
    at Promise (/Users/myusername/Projects/others/wmail/packager/ElectronBuilder.js:92:33)
    at Function.packageSinglePlatformArch (/Users/myusername/Projects/others/wmail/packager/ElectronBuilder.js:69:12)
    at acc.then (/Users/myusername/Projects/others/wmail/packager/ElectronBuilder.js:120:49)
    at process._tickCallback (internal/process/next_tick.js:103:7) code: 'MODULE_NOT_FOUND' }
```

* Which version of WMail are you using? [e.g. 1.3.1]
2.0.8
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OSX 10

**Comment by Thomas101** [comment]
Hi, Have you been able to get the app running locally with `npm start`? Does `src/app/node_modules/wmail-spellchecker/package.json` exist? This is where the version in bin will be copied from

**Comment by Martindelataille** [comment]
@Thomas101 I no longer have this problem but a few others.

I think it should have a problem with path.
You have a src folder here: https://github.com/Thomas101/wmail/tree/master/src/app which mean that path are wmail/tree/master/src/app/src/app

In AppAnalytics.js and AuthGoogle.js, you define relative path 
const credentials = require('../shared/credentials') so it's a problem if you moved folder and files.

https-proxy-agent is missing from package.json too.
const HttpsProxyAgent = require('https-proxy-agent') in AuthGoogle.js

**Comment by Thomas101** [comment]
WMail is actually built up of a number of smaller repositories...
1.) Main Thread `src/app`
2.) Mailboxes Window `src/scenes/mailboxes`
3.) Injected Webview Code `src/scenes/platform`
4.) Shared code available in 1, 2 and 3 `src/shared`
... when you run `npm start` webpack moves all these into the bin folder, compiles a few bits, throws away some un-needed code etc.

This means that the paths used when running actually reflect the paths in the bin directory rather than the source one. It's not an ideal way to do things, but prior to version 2.*.* there was a lot of un-used npm repositories included in the production build and doing this allowed me to reduce the filesize by 17% and files by 95%.

As regards moving files or folders, if I did move them or change the build scripts, then I need to take the hit of refactoring the includes. One alternative to this is to get webpack to do more and alias paths so that they're not so relative, but compiling the main thread with webpack has proved difficult in the past as it's designed more for web than server.
