### ISSUE TITLE
Master password

### ISSUE THREAD

**Issue by AGonLen** [Thomas101/wmail#505]
This is not an issue per-se, would be more an improvement.
What about a being able to set a Master Password at the start of the program, to avoid other users to you may borrow your laptop to connect and view all your accounts?

**Comment by Thomas101** [comment]
I can definitely see the value in this. Encrypting the data that I drop on disk would be pretty easy however the data that chromium uses is where the problem lies.

WMail uses Chromium under the hood and that stores the cookies and localStorage data it uses to access Google straight on disk with no encryption. I could try encrypting this data, then decrypting when the password is entered so chromium can access and provide wmail with access to each account, however whilst the app is open or if the app were ever to quit unexpectedly it would leave the unencrypted data on disk for anyone to grab.

This obviously leaves a giant security hole. I don't imagine adding support for this is on the Chromium teams list and it would be a huge task to integrate this into Chromium from a 3rd party perspective.

From a technical perspective the only thing that I think would work without any security holes, is I could set wmail up to not persist the cookie data at all for a certain account (i.e. keep it in memory only). This would however mean that you'd need to re sign in to google every time you launch wmail. It's basically like going incognito and wouldn't provide any advantage over loading gmail in your browser.

Arguably I could overlook the potential security holes and provide a password block to prevent access to an account using wmail. However because the data is up for grabs on disk I wouldn't feel comfortable providing this level of assurance to users knowing that it could be so easily hacked.

I'll keep an eye on the tech stack going forwards though. In an ideal world I would love to be able to add this, but at the moment it's not technically feasible.

**Comment by AGonLen** [comment]
Thanks for looking into this. I thought it was a good idea.
As you said, if you can keep an eye on the tech stack going forwards would be great!
