### ISSUE TITLE
Frequent reloads of Services tabs

### ISSUE THREAD

**Issue by zk3855** [Thomas101/wmail#563]
* Which version of WMail are you using? [e.g. 1.3.1]
2.0.9 Prerelease

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10 Pro 64bit

I have WMail configured with two accounts, both GMail. The first has Calendar and Contacts "tabs" enabled, the second one the Keep tab.

While the two GMail tabs are always in memory, even when WMail has been running in the background for some time, especially the Keep tab keeps reloading (no pun intended) if it was not accessed fairly recently. For example, switching to one of the GMail tabs for 5 minutes will make the Keep tab reload on the next visit. Same happens with the other non-GMail Service tabs.

I do not experience this behavior when I have Keep open as a tab in the Chrome browser. By the way, the machine has 16GB of RAM.

Is it possible to keep the Keep tab in memory longer (again, no pun intended)?

If this was done as an intended decision to save memory, I would suggest to provide a setting to keep all/some of the service tabs in memory, because reloading of the Keep tab is especially slow.

**Comment by Thomas101** [comment]
I like the puns :)

It's an intentional behaviour to save memory, but you can set WMail to keep keep in memory ;-). 

Head to your settings and go to your account. Under the services section you'll see Calendar, Contacts, Keep etc and next to each one a `Sleepable` checkbox. Just untick this for each service you don't want to sleep and it will hang around the same way the Gmail does

**Comment by zk3855** [comment]
Oh, I totally did not see the checkboxes, even though I changed the order of the services some days ago. I'll keep it in mind (and memory) for the future (pun intended).

Thanks!
