### ISSUE TITLE
WMail slower to restore with one method

### ISSUE THREAD

**Issue by james-clark-5** [Thomas101/wmail#566]
* Which version of WMail are you using? [e.g. 2.0.9]

* Which Operating System are you using? [e.g. Windows 10 64-bit]

If I close the WMail app by hitting the upper-right cross button, the app will then open up instantly if I hit the mini icon near the clock. If I open the app with the large taskbar icon, it takes a second to load.

**Comment by Thomas101** [comment]
Hi,

This is down to the way that apps run in single-instance mode on windows. Using the two different ways of re-opening WMail does two very different things. When you press the close icon in the upper-right WMail is still running in the background and just the hides the UI away.

When you use the mini icon near the clock this icon is from the already setup and running WMail instance. It just tells WMail to re-open the main window and it's done.

When you use the taskbar icon, it starts an entirely new version of WMail which on launch checks to see if WMail is already running. If it is already running, it tells the currently running version to re-show its window and shuts itself back down. This is obviously a far more cpu intensive task hence the delay. There's not really any other way around getting the same behaviour without doing this ghost launch at the moment.

If you want to use the taskbar icon to re-launch the currently running version, minimize the main window rather than closing it. This should see it launch at the same speed as using the mini icon

**Comment by james-clark-5** [comment]
Thanks for the detailed explanation of this process! 
From what you've said, having the reliability of the ghost instance and the check sounds like the best design choice - makes sense.
