### ISSUE TITLE
How to install WMail on PcLinuxOs  ??

### ISSUE THREAD

**Issue by andrea66vi** [Thomas101/wmail#667]
Hello, i wish to install WMail on a PcLinuxOs (32 bit) distro named Uplos  downloaded from NLUUG, because the support for 32bit is ended and my netbook is too old to install 64bit version.

I have tried to convert the .deb file installation of Wmail with Alien, but the generated .rpm file is not good to install the package.

There is a different way to install the Wmail on the distro PcLinuxOs 32b ??

If someone know how to , please write a little tutorial with the command line.

Thank you. Bye

**Comment by MggMuggins** [comment]
Download the 32 bit tarball ([https://github.com/Thomas101/wmail/releases/download/v2.3.0/WMail_2_3_0_linux_ia32.tar.gz) instead of the deb file. There should be an executable file in there that you can run that should work. You can then put the contents of that tarball wherever you'd like on your filesystem. No command line needed. :P

**Comment by andrea66vi** [comment]
Perfect, i resolved the problem.

Thank you.

**Comment by MggMuggins** [comment]
No problem.
