### ISSUE TITLE
Option of a browser when clicking on a link

### ISSUE THREAD

**Issue by ashwinmt** [Thomas101/wmail#78]
This is a personal feature request.

I see that the app runs chromium but when I click on a link, my default browser (safari) opens up. It would be great to throw in a quick popup or a configurable setting to open this in Chrome which is my browser of choice.

**Comment by Thomas101** [comment]
Hi @ashwinmt just to double check I understand, you've got safari set as the default browser but you want to be able to right click and open links in chrome, or firefox etc?

**Comment by vitorgalvao** [comment]
This is a weird request. Most apps don’t do this, for good reason (if you set a default, why are you trying to open another?).

Rather than baking this unusual feature in the app, you (@ashwinmt) should look into (and would be better served) into one of the multitude of apps that exist specifically for this. Among them:

+ [Choosy](https://www.choosyosx.com/).
+ [MultiBrowser](https://sites.google.com/site/tesseractsoftware/multibrowser).
+ [Buffet](https://itunes.apple.com/ua/app/buffet/id1048695921?mt=12).
+ [BrowserSelect](https://github.com/zumoshi/BrowserSelect) (Windows).

**Comment by itamaro** [comment]
> Rather than baking this unusual feature in the app, you (@ashwinmt) should look into (and would be better served) one of the multitude of apps that exist specifically for this. Among them:
> 
> Choosy.
> MultiBrowser.
> Buffet.
> BrowserSelect (Windows).

I use Choosy, but I configure it to use the "best running browser" by default, because usually that works fine. Sometimes I want a specific browser for a specific link, and then the "Open with Choosy" context menu option is useful (in Safari):

![option_of_a_browser_when_clicking_on_a_link_ _issue__78_ _thomas101_wmail](https://cloud.githubusercontent.com/assets/290943/12944134/e8cd9370-cfed-11e5-8f52-456ee8691940.png)

This is not available in Wmail context menu:

![wmail](https://cloud.githubusercontent.com/assets/290943/12943997/53f1241a-cfed-11e5-8e15-d94cd58cfeb1.png)

How come?

**Comment by vitorgalvao** [comment]
@itamaro Because Wmail uses [Electron](https://github.com/atom/electron), and those options aren’t available by default. Not sure they can be added easily, would have to check.

**Comment by Thomas101** [comment]
By the looks of it choosy is just using a chrome extension to integrate into the menu. Electron does support running chrome extensions, but I don't know to what extent yet. Maybe it would be worth taking a look into that to get this running?

**Comment by vitorgalvao** [comment]
@Thomas101 Just in general, I believe extensions would be worth having, as that would make gmail-centric extensions (like [writting in markdown](http://markdown-here.com/)) feasible.

**Comment by Thomas101** [comment]
Hi, I think this would be best suited as an extension if possible. I'm creating an issue just for extensions which is here #103. I've added markdown and choosy to the list already :)
