### ISSUE TITLE
'Bundled' emails are triggering the 'new email' notification

### ISSUE THREAD

**Issue by dep** [Thomas101/wmail#89]
If I get an email in Google Inbox that is set to be bundled and skip the inbox, I am getting a new mail notification about this. I should only get a notification when a new message actually appears *in* the inbox.

Same for 'unread' badges. It's also considering bundled, unread emails as badged emails.  The badge should just reflect stuff that's in the inbox.

**Comment by lament** [comment]
Go to your settings, under Accounts, choose your Inbox account and select "Messages in Inbox."

**Comment by Thomas101** [comment]
Hi @dep does that fix the issue for you?

**Comment by itamaro** [comment]
Changing to "Messages in Inbox" changes the badge to all the messages in inbox. I don't think that was the intention. At least for me, I would like the badge to show only unread message that are currently shown in my Inbox, not including messages that are in bundles that are configured to be shown only once per day, and are not shown at the moment.

**Comment by itamaro** [comment]
> Changing to "Messages in Inbox" changes the badge to all the messages in inbox. I don't think that was the intention. At least for me, I would like the badge to show only unread message that are currently shown in my Inbox, not including messages that are in bundles that are configured to be shown only once per day, and are not shown at the moment.

Everything I said about badges is also true for "new email" notifications, which is actually the subject of this issue... :-)

**Comment by dep** [comment]
@Thomas101 didn't fix my issue, no.  Changing that dropdown seems to have no effect, really.

**Comment by Thomas101** [comment]
Looking into this, google might be using the inbox category labels as bundle options. Will need to investigate further

**Comment by phuibonhoa** [comment]
This also affects bundled messages that you have set to be delivered daily/weekly.  The expected behavior I believe is that bundled messages are not counted towards the badge until they are delivered to the inbox.  

Right now I may have a bundle set to be delivered daily that has 5 messages, but the bundle technically has not yet been delivered to my inbox.  Those 5 messages appear in the unread badge number even though they are not in my inbox yet.  When the daily delivery triggers, only then should the badge number increase.  

![wmail](https://cloud.githubusercontent.com/assets/14584/13278682/255ef3bc-da87-11e5-9a28-2116930054a7.jpg)

**Comment by sankaritan** [comment]
+1. The fact that bundled messages - that are yet to appear in the inbox in the future are shown as new mail notifications - is really annyoing. Basically one has to remember the count in order to see whether there are in fact any new messages available now. Had a quick look at the gmail api and could not see bundled mentioned there :( Maybe I just missed it though..

**Comment by Thomas101** [comment]
@sankaritan when I looked I couldn't find anything in the gmail api. My thought was to try and sniff what's going on in the dom to pick out bundled messages vs non bundles ones. I've just not had time to investigate if this will work or not

**Comment by Thomas101** [comment]
Hi, I'm going to close this and collapse it into #349 as there's a few issues surround some Google Inbox Notifications and unread counts which are all related. Thanks!
