### ISSUE TITLE
Unread notification does not refresh properly

### ISSUE THREAD

**Issue by fane89** [Thomas101/wmail#96]
Hi,

here are some examples of the bug.

The unread icon does not refresh after operation on the inbox.

![zrzut ekranu 2016-02-11 o 08 47 13](https://cloud.githubusercontent.com/assets/9295830/12972494/0b69fd5c-d0a6-11e5-88bd-6c58c6a886ff.png)
![zrzut ekranu 2016-02-11 o 08 47 25](https://cloud.githubusercontent.com/assets/9295830/12972493/0b6906cc-d0a6-11e5-8af2-1bbd6ed08c30.png)
![zrzut ekranu 2016-02-11 o 08 47 42](https://cloud.githubusercontent.com/assets/9295830/12972495/0b6ba184-d0a6-11e5-889e-bfa30637fd44.png)

**Comment by Thomas101** [comment]
Hi, if you right click on the selector on the left and then go to reload does it update?

**Comment by fane89** [comment]
yes

**Comment by Thomas101** [comment]
Okay, it looks like it's not refreshing automatically. Can you try the following...
1.) Send yourself an email so the notification goes up to 1.
2.) Open the email so it becomes read, then do nothing for 5 seconds (don't click in the client at all).
Does it go back down to zero now?

**Comment by fane89** [comment]
After not doing anything it goes to zero.

**Comment by Thomas101** [comment]
Okay, this is because the unread counts and notifications are pulled in a separate api call as to what you see in the inbox view. I've had to put some limiting on as to not exceed the quotas that google impose.

The behaviour at the moment is that the app checks every minute, then every time you click in the window it waits 2.5 secs to see if you click again and if you don't it asks for an update.

Ideally it would be great to sniff what you see in the inbox view to get the unread count as and when it actually changes. I need to improve the notifications which will affect this as well... I think probably a re-think on the code side so hopefully I can get it updating immediately.

**Comment by fane89** [comment]
Update from watching what happens on the user side would be great. Then
from time to time sync with server.

**Comment by Thomas101** [comment]
Hello! I've added this into the latest pre-release (1.2.1) which is available on the [downloads page](http://thomas101.github.io/wmail/download) or from the [direct link](https://github.com/Thomas101/wmail/releases/download/v1.2.1/WMail_1_2_1_osx_prerelease.zip). 

Thanks for your help!

**Comment by fane89** [comment]
Thanks !
